server:
  port: 8040
spring:
  application:
    name: self-base
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: root
  redis:
    password: fuck
    host: localhost
    port: 6379
  rabbitmq:
    host: localhost
    port: 5672
    username: root
    password: 123456
    virtual-host: /

mybatis:
  type-aliases-package: com.self.base.client.domain
  configuration:
    logImpl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

logging:
  level:
    root: INFO
  pattern:
    console: '%d{yyyy/MM/dd-HH:mm:ss} [%thread] %-5level %logger [%L]- %msg%n'
    file: '%d{yyyy/MM/dd-HH:mm:ss} [%thread] %-5level %logger [%L]- %msg%n'
  file:
    name: logs/data.log

eureka:
  client:
    service-url:
      defaultZone: http://localhost:1111/eureka/
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    prefer-ip-address: true

self:
  cache:
    redis:
      expire: 60