#访问端口号
server:
  port:
    8030
  servlet:
    context-path: /selfFrame

#数据库相关配置
spring:
  #应用名称
  application:
    name: self-frame
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: root
  redis:
#    cluster:
#      nodes:
#        - 192.168.11.138:6380
#        - 192.168.11.138:6381
#        - 192.168.11.138:6382
#        - 192.168.11.138:6383
#        - 192.168.11.138:6384
#        - 192.168.11.138:6385
#      max-redirects: 3
    password: fuck
#    host: 192.168.197.130
    host: localhost
    port: 6379
  rabbitmq:
    host: localhost
    port: 5672
    username: root
    password: 123456
    virtual-host: /
mybatis:
  type-aliases-package: com.self.backend.domain
  configuration:
    logImpl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
pagehelper:
  helperDialect: mysql
  offset-as-page-num: true
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
logging:
  level:
    root: INFO
  pattern:
    console: '%d{yyyy/MM/dd-HH:mm:ss} [%thread] %-5level %logger [%L]- %msg%n'
    file: '%d{yyyy/MM/dd-HH:mm:ss} [%thread] %-5level %logger [%L]- %msg%n'
  file:
    name: logs/data.log

self:
  cache:
    redis:
      expire: 60

eureka:
  client:
    service-url:
      defaultZone: http://localhost:1111/eureka/
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    prefer-ip-address: true